In [6]:
import torch

In [8]:
z = torch.zeros(5,3)
print(z)
print(z.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


In [9]:
i = torch.ones((5,3), dtype = torch.int16)
print(i)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


In [11]:
torch.manual_seed(1729)
r1 = torch.rand(2,2)
print('Á random Tensor:')
print(r1)

r2 = torch.rand(2,2)
print('A different Random Tensor:')
print(r2)

torch.manual_seed(1729)
r3 = torch.rand(2,2)
print('Should Match R1:')
print(r3)

Á random Tensor:
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])
A different Random Tensor:
tensor([[0.4216, 0.0691],
        [0.2332, 0.4047]])
Should Match R1:
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])
